import React from "react";
import { View, Text, StyleSheet, Pressable, ScrollView, Platform, Animated, Alert } from "react-native";
import { getTheme } from "../utils/theme";

const HelpSupportScreen_uipro = ({ onBack, isDarkMode = true }) => {
  const T = getTheme(isDarkMode);

  const fade = React.useRef(new Animated.Value(0)).current;
  const slide = React.useRef(new Animated.Value(20)).current;

  React.useEffect(() => {
    Animated.parallel([
      Animated.timing(fade, { toValue: 1, duration: 600, useNativeDriver: true }),
      Animated.timing(slide, { toValue: 0, duration: 600, useNativeDriver: true }),
    ]).start();
  }, []);

  const FAQS = [
    { q: "What is SkillGenome Score?", a: "Your SkillGenome score is an aggregated readiness indicator generated by combining your resume, GitHub repos, and interview performance." },
    { q: "How do I connect my GitHub?", a: "Navigate to the GitHub Connect screen from your profile or settings page and enter your public GitHub username." },
    { q: "Are AI mock interviews recorded?", a: "Your responses are evaluated locally and via AI APIs to generate real-time metrics. Audio streams are not permanently stored." },
  ];

  return (
    <View style={[S.root, { backgroundColor: T.bg }]}>
      <View style={S.header}>
        <Pressable style={[S.iconBtn, { backgroundColor: T.surface, borderColor: T.border }]} onPress={onBack}>
          <Text style={[S.iconBtnText, { color: T.text }]}>←</Text>
        </Pressable>
        <Text style={[S.pageTitle, { color: T.text }]}>Help & Support</Text>
        <View style={{ width: 42 }} />
      </View>

      <ScrollView contentContainerStyle={S.content} showsVerticalScrollIndicator={false}>
        <Animated.View style={{ opacity: fade, transform: [{ translateY: slide }], gap: 20 }}>
          
          <View style={[S.contactCard, { borderColor: T.accent, backgroundColor: `${T.accent}10` }]}>
            <Text style={[S.contactTitle, { color: T.text }]}>Need direct assistance?</Text>
            <Text style={[S.contactSub, { color: T.muted }]}>Our support team is available 24/7 to help you resolve any issues.</Text>
            <Pressable style={[S.contactBtn, { backgroundColor: T.accent }]} onPress={() => Alert.alert("Support Email", "Contact us at support@skillgenome.ai")}>
              <Text style={S.contactBtnText}>Contact Support</Text>
            </Pressable>
          </View>

          <Text style={[S.sectionTitle, { color: T.muted }]}>FREQUENTLY ASKED QUESTIONS</Text>
          <View style={S.faqList}>
            {FAQS.map((f, i) => (
              <View key={i} style={[S.faqCard, { borderColor: T.border, backgroundColor: T.surface }]}>
                <Text style={[S.faqQ, { color: T.text }]}>{f.q}</Text>
                <Text style={[S.faqA, { color: T.muted }]}>{f.a}</Text>
              </View>
            ))}
          </View>

        </Animated.View>
      </ScrollView>
    </View>
  );
};

const S = StyleSheet.create({
  root: { flex: 1 },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: Platform.OS === "ios" ? 54 : 28, paddingHorizontal: 20, paddingBottom: 16 },
  iconBtn: { width: 42, height: 42, borderRadius: 21, borderWidth: 1, alignItems: "center", justifyContent: "center" },
  iconBtnText: { fontSize: 18, fontWeight: "600" },
  pageTitle: { fontSize: 18, fontWeight: "800", letterSpacing: -0.4 },

  content: { paddingHorizontal: 20, paddingBottom: 40, maxWidth: 600, width: "100%", alignSelf: "center" },
  contactCard: { padding: 20, borderRadius: 20, borderWidth: 1, gap: 10 },
  contactTitle: { fontSize: 18, fontWeight: "800" },
  contactSub: { fontSize: 13, lineHeight: 20 },
  contactBtn: { paddingVertical: 14, borderRadius: 12, alignItems: "center", marginTop: 6 },
  contactBtnText: { color: "#fff", fontWeight: "800", fontSize: 14 },

  sectionTitle: { fontSize: 11, fontWeight: "700", letterSpacing: 1, marginLeft: 4 },
  faqList: { gap: 12 },
  faqCard: { padding: 18, borderRadius: 18, borderWidth: 1, gap: 8 },
  faqQ: { fontSize: 15, fontWeight: "700" },
  faqA: { fontSize: 13, lineHeight: 20 },
});

export default HelpSupportScreen_uipro;
