-- SQL Migration Script to create public.emotions table for EmotionPrint tracking
CREATE TABLE IF NOT EXISTS public.emotions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    audio_path text,
    duration integer,
    stress_index integer,
    confidence_index integer,
    analysis_data jsonb, -- Stores the full emotion analysis payload for easy JSON loading
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.emotions ENABLE ROW LEVEL SECURITY;

-- Allow all public operations for development
CREATE POLICY "Allow public insert and select for emotions" ON public.emotions
    FOR ALL USING (true) WITH CHECK (true);
